### ISSUE TITLE
Sound files

### ISSUE THREAD

**Issue by wd5m** [AllStarLinkInc/ASL-Live-Build#10]
I noticed differences in audio files in the beta under /var/lib/asterisk/sounds/, at least compared to my VPS Allstar that was installed from the ISO a few months ago.  Some of this may just be cleanup of duplicate files, which I agree with.  I found one file under .../sounds/rpt/connecting.ulaw, instead of .../sounds/connecting.ulaw.  However, there seem to be some that don't exist on the beta, such as connected.ulaw.

**Comment by robvella** [comment]
I'll compare the two and make sure any missing are in the next beta. Thanks!
