### ISSUE TITLE
Not a bug - feature request/wishlist...

### ISSUE THREAD

**Issue by JimAspinwall** [AllStarLinkInc/ASL-Live-Build#11]
2.0 setup so far, so good !!! ... now to commit an active radio node to it and let it run.

With Apache now included... consider an HTML interface 'atop' asl-menu.  One could theoretically populate most/all of the variables for node ID, password, port(s), radio interface, potentially white-/black-lists, private nodes, etc.  then plug them into the various scripts/command-lines to get through config to live.  Maybe?

About to build 4 private nodes for a community public-service entity.  If the newer OS is stable, and we know Asterisk, iaxrpt reliable... some things to consider.

**Comment by robvella** [comment]
Thanks for the input.

We're already working on this now -- It'll be a few months, but the plan is to create an interface that includes Allmon like functionality, last heard, and complete node administration. It'll dramatically simplify the node experience and make it easier for people to setup.

Thanks for trying to the beta!

**Comment by JimAspinwall** [comment]
2.0 now running my garage node!  Now to 'clone' it onto my portable node.
