### ISSUE TITLE
Unresponsive on Pi2 and Pi4

### ISSUE THREAD

**Issue by kyle470** [AllStarLinkInc/ASL-Live-Build#15]
Gave the beta a try on a Pi2 a few days ago. Noticed some odd behavior, such as commands not being acted upon in Asterisk. Shutdown now, and rpt fun commands had no effect. Shut down Pi, but the shutdown process took about 5 minutes. 

Today I tried a Pi4 on the beta with similar results. I'm not sure what's causing the OS to hang up, but killing Asterisk seemed to cure the problems. Went ahead and installed 2 fobs, the audio was very delayed and dropped in the middle of a *70.

I saw just now that a newer Beta is available, although I didn't see anything in the changelogb mentioning OS hangs. I'll try a fresh Beta install again soon. Thanks for all of your work.

Kyle
K0KN

**Comment by robvella** [comment]
Hi Kyle -- can you e-mail me at rob@allstarlink.org. Happy to help diagnose your issues.

**Comment by robvella** [comment]
Investigating issue.

**Comment by tsawyer** [comment]
Kyle. Please try a fresh install w/o making changes. Don't use any menus, add any configs or scripts. Is the performance still degraded?

**Comment by kyle470** [comment]
Good afternoon,

I've started over using Beta .5 this time, and not yet experiencing any
issues. I'll proceed with setting up my nodes and give those a try.

On my previous setup (Beta .1) that had issues, it was pretty bare-bones
without any scripts or major config changes. I had basically just set a
static IP only.

Thanks. 73
