### ISSUE TITLE
Stanza to define LAN or Private Nodes 

### ISSUE THREAD

**Issue by fpuigb** [AllStarLinkInc/ASL-Live-Build#17]
**Describe the bug**
In previous versions there is a stanza called [nodes] where the users can define by IP, private or local (LAN) connected nodes, this is missing or have been changed. 
 
**To Reproduce**
Node stanza missing from rpt.conf

**Expected behavior**
Two nodes can be defined to be connected back to back inside a LAN. 

**Version**
AllStarLink ASL 2.0.0-beta5

**Additional context**
Stanza example:

[nodes]
; Note, if you are using automatic updates for allstar link nodes,
; no allstar link nodes should be defined here. Only place a definition
; for your local (within your LAN) nodes, and private (off of allstar
; link) nodes here.

12345 = radio@192.168.1.20/12345,NONE

**Comment by robvella** [comment]
Hello - 

The [nodes] stanza in beta.5 has been moved to the top of the file.

**Comment by fpuigb** [comment]
> Hello -
> 
> The [nodes] stanza in beta.5 has been moved to the top of the file.

My bad, you right. Thanks
