### ISSUE TITLE
Unable to set manager password via asl-menu

### ISSUE THREAD

**Issue by mitchmitchell** [AllStarLinkInc/ASL-Live-Build#2]
I cannot get asl-menu to save off the asterisk-secret into the conf files.  It appears to take it but never actually writes out the information into either manager.conf or a configuration file under manager.d/*.conf

It may be related to a message that is spit out on stderr (I think) while running asl-menu:
"sed: -e expression #1, char 0: no previous regular expression"

**Comment by robvella** [comment]
Thanks for the info! We'll push something in the next release.

**Comment by robvella** [comment]
I'm not able to reproduce this issue with the latest beta build. It seems to properly put the new password in.

What beta version are you running?
