### ISSUE TITLE
Removing PRs?

### ISSUE THREAD

**Issue by McLovinIts** [AllStarLinkInc/ASL-Live-Build#5]
Kindly explain how you are removing PRs that state the ASL Live Build is not properly attributing the creators? 

Instead I receive a passive aggressive reply via email and now the PR is missing.

The GPL v3 requires attribution by keeping existing copyright notices and acknowledge the author(s).

Yet the ASL Live Build maintainers have decided to play games and state otherwise?  

This is not a troll comment.  I strongly suggest you read the GPL v3 and stop being so thin skinned when it comes to valid constructive criticism.

I hereby state you are in violation of the GPL v3 for the debian live build and demand you remedy this.

**Comment by robvella** [comment]
We're not "basing" our software on Debian Live Build - we're using Debian live-build as a way to generate images. No portion of Debian live build is included in this repository.
